[build]
  command = "npm install && npm run build-frontend"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "https://farmers-backend-rty2.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "https://farmers-backend-rty2.onrender.com/health"
  status = 200
  force = true